sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO

title: "OxfordHack 2020" # the name of your site, e.g. ACME Corp.
tagline: "Welcome to OxfordHack 2020"
email: technical@oxfordhack.co.uk
description: >- # this means to ignore newlines until "baseurl:"
 Bottom Text
author: OxfordHack 2020
baseurl: /oxfordhack_landing_page
url: "https://ilmanfordinner.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#google_analytics: UA-111111111-1
#twitter:
#  username: 
#  card: summary #keep this to generate a twitter share card